A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('category/', include('category.urls', namespace='category')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'
urlpatterns = [
    path('', views.ProductView.as_view(), name='products'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product'),
    path('<slug:category_slug>/', views.ProductView.as_view(), name='category_filter'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='post_reply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('carete/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
]

category/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User


# Create your models here.

class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return f'{self.name} - {self.slug}'

    def get_absolute_url(self):
        return reverse('category:category_filter', args=(self.slug,))


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name} - {self.price} - {self.available}'

    def get_absolute_url(self):
        return reverse('category:product', args=(self.slug,))


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

category/forms.py
from django import forms
from .models import Comment


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'style': 'margin-left:10px; width:50%'})
        }
        labels = {
            'body': 'hello'
        }

category/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Category, Comment
from orders.forms import CartAddForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentReplyForm, CommentCreateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


# Create your views here.

class ProductView(View):
    template_name = 'category/index.html'

    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, self.template_name, {'products': products, 'categories': categories})


class ProductDetailView(View):
    template_name = 'category/detail.html'
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instead = get_object_or_404(Product, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        comments = self.post_instead.pcomments.filter(is_reply=False)
        form = CartAddForm
        return render(request, self.template_name,
                      {'product': product, 'form': form, 'comments': comments, 'form_comment': self.form_class,
                       'reply_form': self.form_class_reply})

    @method_decorator(login_required())
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_commend = form.save(commit=False)
            new_commend.user = request.user
            new_commend.post = self.post_instead
            new_commend.save()
            messages.success(request, 'your comment added for this form (language level up)', 'success')
            return redirect('category:product', self.post_instead.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Product, pk=post_id)
        comment = get_object_or_404(Comment, pk=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.post = post
            new_reply.reply = comment
            new_reply.is_reply = True
            new_reply.save()
            messages.success(request, 'your reply been added :)', 'success')
        return redirect('category:product', post.slug)

category/templates/category/detail.html
{% extends 'base.html' %}

{% block title %}
    Detail | Page
{% endblock %}

{% block extra_header %}
    <style>
        .quantity {
            background-color: #343a40;
            border-radius: .3rem;
            padding: 5px;
            color: #fff;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2> {{ product.name }} </h2>
        <small> {{ product.created }} </small>
        <p> {{ product.description }} </p>
        <p> {{ product.price }} $</p>
        <img src="{{ product.image.url }}" alt="" class="col-md-3 m-4">
        <br>
        <form action="{% url 'orders:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Cart" class="btn btn-warning col-md-3">
        </form>
    </div>
    <br><br>
    <hr>
    {% if request.user.is_authenticated %}
        <p class="text-center" style="font-size: 1.5rem"><strong> Add Comment </strong></p>
        <form class="col-md-5" action="" method="post" novalidate>
            {% csrf_token %}
            {{ form_comment.as_p }}
            <input type="submit" value="Send" class="btn btn-primary">
        </form>
    {% else %}
        <p class="text-center"> Oops... Only logged users can send commend. you can log in with this <strong><a
                href="{% url 'accounts:user_login' %}">link</a></strong></p>
    {% endif %}
    <br>
    <hr>
    <p class="text-center" style="font-size: 1.5rem"> ' <strong>{{ comments.count }}</strong> commends ' </p><br>
    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header"> {{ comment.user }} | {{ comment.created|timesince }} </p>
            <p class="card-body"> {{ comment.body }} </p>
            {% with replies=comment.rcomments.all %}
                {% for reply in  replies %}
                    <p class="bg-primary text-white p-3 m-2">{{ reply.user }} <br> {{ reply.body }}</p>
                {% endfor %}
            {% endwith %}
            {% if request.user.is_authenticated %}
                <form class="col-md-8" action="{% url 'category:post_reply' product.id comment.id %}" method="post" novalidate>
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input type="submit" value="Send" class="btn btn-primary" style="width: 50%; margin: 0 0 10px 10px">
                </form>
            {% endif %}
        </div><br>
        {% empty %}
        <p class="text-center"> There is no comments ! </p>
    {% endfor %}

{% endblock %}

category/templates/category/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Category | Page
{% endblock %}

{% block extra_header %}
    <link rel="stylesheet" href="{% static 'category/css/style.css' %}">
{% endblock %}

{% block content %}

    <div>
        <h2 class="font-weight-normal text-center"
            style="color: #000; padding: 10px;border-radius: .3rem;width: 21.67%"><strong>categories</strong></h2>
        <a href="{% url 'category:products' %}" class="btn btn-outline-dark">All</a>
        {% for category in categories %}
            <div class="btn-group">
                <a class="btn btn-danger" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="visually-hidden"></span>
                </button>
                <ul class="dropdown-menu">
                    {% for sub in category.scategory.all %}
                        <li>
                            <a href="{{ sub.get_absolute_url }}" class="dropdown-item">{{ sub.name }}</a>
                        </li>
                    {% endfor %}
                </ul>

            </div>
        {% endfor %}
    </div>
    <br><br>


    {% for product in products %}
        <div class="card category d-inline-block">
            <img src="{{ product.image.url }}" class="card-img-top p-3" alt="">
            <di class="card-body">
                <h5 class="card-title"> {{ product.name }} </h5>
                <hr>
                <p class="card-text"> {{ product.created }} </p>
                <a href="{{ product.get_absolute_url }}" class="btn btn-primary"> Detail </a>
            </di>
        </div>
    {% endfor %}

{% endblock %}