A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('category/', include('category.urls', namespace='category')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('carete/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
]

orders/models.py
from django.db import models
from django.conf import settings
from category.models import Product
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
    pied = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.IntegerField(blank=True, null=True, default=None)
    address = models.TextField(max_length=200, blank=True, null=True, default=None)
    RefID = models.IntegerField(blank=True, null=True, default=None)

    class Meta:
        ordering = ('pied', '-updated')

    def __str__(self):
        return f'{self.user} - {self.id}'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=15, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code

orders/forms.py
from django import forms
from .models import Order


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)


class CouponApplyForm(forms.Form):
    code = forms.CharField(
        label='Coupon Code ',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control col-md-3'
            }
        )
    )


class AddressForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'address',
        )
        labels ={
            'address': 'Address '
        }

        def __init__(self, *args, **kwargs):
            super(AddressForm, self).__init__(*args, *kwargs)
            self.fields['address'].widget.attrs['placeholder'] = 'Please enter your address:'
            self.fields['address'].widget.attrs['class'] = 'form-control col-md-3'

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .cart import Cart
from .forms import CartAddForm, CouponApplyForm, AddressForm
from category.models import Product
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order, OrderItem, Coupon
import datetime
from django.contrib import messages
from django.http import HttpResponse
from django.conf import settings
from suds.client import Client


# Create your views here.

class CartView(View):
    template_name = 'orders/cart.html'

    def get(self, request):
        cart = Cart(request)
        return render(request, self.template_name, {'cart': cart})


class CartAddView(View):

    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class OrderDetailView(LoginRequiredMixin, View):
    form_class = CouponApplyForm
    form_address = AddressForm
    template_name = 'orders/order.html'

    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        return render(request, self.template_name,
                      {'order': order, 'form': self.form_class, 'form_address': self.form_address})

    def post(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        address = request.POST['address']
        order.address = address
        order.save()
        messages.success(request, 'your address added. now you can pey the order', 'success')
        return redirect('orders:order_detail', order_id)



class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        if len(cart) == 0:
            messages.warning(request, 'Your cart is empty !', 'warning')
            return redirect('orders:cart')
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                     quantity=item['quantity'])
        cart.clear()
        return redirect('orders:order_detail', order.id)


class CouponApplyView(View):
    form_class = CouponApplyForm

    def post(self, request, order_id):
        now = datetime.datetime.now()
        form = self.form_class(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            try:
                coupon = Coupon.objects.get(code=code, valid_from__lte=now, valid_to__gte=now, active=True)
            except Coupon.DoesNotExist:
                messages.error(request, 'coupon is not exist!', 'danger')
                return redirect('orders:order_detail', order_id)
            order = Order.objects.get(id=order_id)
            order.discount = coupon.discount
            order.save()
        return redirect('orders:order_detail', order_id)


"""
    Zarinpal config
"""

if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'

ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"
ZARINPAL_WEBSERVICE = f'https://{sandbox}.zarinpal.com/pg/services/WebGate/wsdl'  # Required
CallbackURL = 'http://127.0.0.1:8000/orders/verify/'  # TODO: Important: need to edit for really server.
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required


class OrderPayView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = Order.objects.get(pk=order_id)
        if order.address:
            request.session['order_pay'] = {
                'order_id': order.id,
            }
            client = Client(ZARINPAL_WEBSERVICE)
            result = client.service.PaymentRequest(settings.MERCHANT,
                                                   order.get_total_price(),
                                                   description,
                                                   request.user.email,
                                                   request.user.phone_number,
                                                   CallbackURL)
            if result.Status == 100:
                return redirect(ZP_API_STARTPAY + result.Authority)
            else:
                return HttpResponse('Error')
        messages.error(request, 'Please add your address.', 'danger')
        return redirect('orders:order_detail', order_id)


class OrderVerifyView(LoginRequiredMixin, View):
    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = Order.objects.get(id=int(order_id))
        client = Client(ZARINPAL_WEBSERVICE)
        if request.GET.get('Status') == 'OK':
            result = client.service.PaymentVerification(settings.MERCHANT,
                                                        request.GET['Authority'],
                                                        order.get_total_price(), )
            status_code = result.Status
            if status_code == 100:
                order.pied = True
                order.RefID = result.RefID
                order.save()
                return render(request, 'orders/verify_transaction.html', {'RefID': str(result.RefID)})
            elif result.Status == 101:
                return render(request, 'orders/submitted_transaction.html', {'status_code': status_code})
            else:
                return render(request, 'orders/failed_transaction.html', {'status_code': status_code})
        else:
            return render(request, 'orders/canceled_transaction.html')

orders/templates/orders/canceled_transaction.html
{% extends 'base.html' %}

{% block title %}
    Cancel Payment
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2> Transaction failed ❌ </h2>
        <br>
        <hr>
        <h3> Payment has been cancelled.</h3><br>
        <a href="{% url 'home:home' %}" class="btn btn-outline-primary">Go Home</a><br><br>
        <small class="text-danger"> warning : This is a test payment </small>
    </div>
{% endblock %}

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block title %}
    Cart | Page
{% endblock %}


{% block content %}
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Total Price</th>
            <th scope="col">Remove</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }} $</td>
                <td>{{ item.total_price }} $</td>
                <td><a href="{% url 'orders:cart_remove' item.product.id %}" class="btn btn-danger">Remove</a></td>
            </tr>
        {% endfor %}

        <tr>
            <th>Total Cart Price</th>
            <td colspan="4"></td>
            <td>{{ cart.get_total_price }} $</td>
        </tr>
        </tbody>
    </table>
    <a href="{% url 'orders:order_create'  %}" class="btn btn-outline-primary"> Checkout </a>
{% endblock %}

orders/templates/orders/failed_transactionl.html
{% extends 'base.html' %}

{% block title %}
    Filed Payment
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2> Transaction submitted ❌ </h2>
        <br>
        <hr>
        <h3> Transaction failed : {{ status_code }} </h3><br>
        <a href="{% url 'home:home' %}" class="btn btn-outline-primary">Go Home</a><br><br>
        <small class="text-danger"> warning : This is a test payment </small>
    </div>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}

{% block title %}
    Order | Page
{% endblock %}

{% block content %}
    <h2> Checkout </h2>
    <p> Total Price : <strong>{{ order.get_total_price }}</strong> Toman </p>
    <a href="{% url 'orders:order_pay' order.id %}" class="btn btn-outline-primary col-md-1"> Pay </a>
    <hr class="col-md-3 ml-1">
    <form action="{% url 'orders:order_detail' order.id %}" method="post" novalidate>
        {% csrf_token %}
        {{ form_address.as_p }}
        <input type="submit" value="Add Address" class="btn btn-primary col-md-1">
    </form><br><br>
    <form action="{% url 'orders:apply_coupon' order.id %}" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Apply" class="btn btn-outline-info col-md-1">
    </form>
{% endblock %}

orders/templates/orders/submitted_transaction.html
{% extends 'base.html' %}

{% block title %}
    Submitted Payment
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2> Transaction submitted ❌ </h2>
        <br>
        <hr>
        <h3> Transaction submitted : {{ status_code }} </h3><br>
        <a href="{% url 'home:home' %}" class="btn btn-outline-primary">Go Home</a><br><br>
        <small class="text-danger"> warning : This is a test payment </small>
    </div>
{% endblock %}

orders/templates/orders/verify_transaction.html
{% extends 'base.html' %}

{% block title %}
    Successful Payment
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2> Transaction success ✅ </h2>
        <br>
        <hr>
        <h4> This is your RefID : {{ RefID }} </h4>
        <h4> Please Write down your refID code. </h4><br>
        <a href="{% url 'home:home' %}" class="btn btn-outline-primary">Go Home</a><br><br>
        <small class="text-danger"> warning : This is a test payment </small>
    </div>
{% endblock %}