A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('category/', include('category.urls', namespace='category')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'
urlpatterns = [
    path('', views.ProductView.as_view(), name='products'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product'),
    path('<slug:category_slug>/', views.ProductView.as_view(), name='category_filter'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='post_reply'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('carete/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags}} m-2">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand btn btn-primary" href="{% url 'home:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active btn btn-danger m-1" href="{% url 'orders:cart' %}">Cart
                <strong>{{ cart|length }}</strong></a>
            <a class="nav-item nav-link active btn btn-info m-1" href="{% url 'category:products' %}">Category</a>
            {% if not request.user.is_authenticated %}
                <a class="nav-item nav-link active btn btn-warning m-1"
                   href="{% url 'accounts:user_register' %}">Register</a>
                <a class="nav-item nav-link active btn btn-light text-dark m-1"
                   href="{% url 'accounts:user_login' %}">Login</a>
            {% else %}
                <a class="nav-item nav-link active btn btn-light text-dark m-1"
                   href="{% url 'accounts:user_logout' %}">Logout</a>
            {% endif %}
        </div>
    </div>
</nav>